// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnbzapctaidczbvnycem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuYnphcGN0YWlkY3pidm55Y2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDA0OTgsImV4cCI6MjA2NTQ3NjQ5OH0.z_pe5_ZdBfCGJ5pNQdeYU1xJ5syN0N3yKzZADwPecYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);